<header>
	<a href="<?php echo RoutesHelpers::IndexHomePath(); ?>" TARGET="_blank" class="logo">
		<img src="../../assets/images/info.png" alt="Logo InfoJr UFBA">
	</a>
	<nav class="menu">
		<ul>
			<a href="#"><li>Excluir Pessoa</li></a>
			<a href="#"><li>Editar Pessoa</li></a>
			<a href="#"><li>Visualizar Pessoa</li></a>
			<a href="<?php echo RoutesHelpers::CreatePersonPath(); ?>"><li>Criar Pessoa</li></a>
		</ul>
	</nav>
</header>
